### ISSUE TITLE
Latest version of black?

### ISSUE THREAD

**Issue by turian** [ricardochaves/python-lint#12]
What version of black does this use? Is it the latest?

On github with this docker I get
```
Running: black --check src
would reformat /github/workspace/src/ddspdrum/module.py
Oh no! 💥 💔 💥
```

On my laptop I have the latest pypi black and get
```
All done! ✨ 🍰 ✨
5 files would be left unchanged.
```

**Comment by ricardochaves** [comment]
The black version is `19.10b0`

What version of action are you using? Depending on the version you use, you may be experiencing [this problem](https://github.com/PyCQA/isort/issues/725). At first it was solved in Isort 5. What version of Isort are you using?

Can you send me your `yml`?

**Comment by turian** [comment]
https://github.com/turian/ddsp-drum/blob/main/.github/workflows/pylint.yml

Thank you

**Comment by alvarovn** [comment]
We are having the same issue with black, not using isort. This is our yml:
```
name: Lint

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: python-lint
        uses: ricardochaves/python-lint@v1.1.0
        with:
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: true
          use-mypy: false
          use-isort: false
          extra-flake8-options: "--max-line-length=99"
          extra-black-options: "--line-length=99"
```
