### ISSUE TITLE
Error:  No module named 'pylint-pytest'

### ISSUE THREAD

**Issue by LorhanSohaky** [ricardochaves/python-lint#15]
I'm new to Python. I'm trying to set up a script to pass the pylint. I managed to configure the pre-commit, but the CI script had a problem

lint.yml
```yml
name: lint
on: [pull_request]
jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install requirements
        run: pip install -r requirements.txt
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          use-pycodestyle: false
          use-black: false
          use-mypy: false
          extra-pylint-options: "--errors-only --rcfile .pylintrc"
```

.pylintrc
```
[MASTER]
init-hook='import sys; sys.path.append(".")'
load-plugins=pylint_pytest
extension-pkg-whitelist=pydantic
```
